# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    # Definición de variables de entorno y variable abierta
    env:
      NOMBRES: Percy
      APELLIDOS: Zavala Muñoz
      EDAD: 30
      VERSION_PROYECTO: 3.0 

    steps:
     
      - uses: actions/checkout@v4
      


      # 1er step:
      - name: presentación # presentación
        run: |
          Imprimir las variables de entorno (NOMBRES, APELLIDOS, EDAD)
          echo "Nombres: $NOMBRES"
          echo "Apellidos: $APELLIDOS"
          echo "Edad: $EDAD"

      # 2do step:
      - name: datos generales # datos generales
        run: |
          Imprimir: "carrera de ingeniería de sistemas"
          echo "carrera de ingeniería de sistemas"
          
      # 3er step (variables secretas):
      - name: variables de entorno secretas # variables de entorno secretas
        run: |
          Imprimir variables secretas (user,password)
          echo "user: ${{secrets.USER}}"
          echo "password: ${{secrets.PASSWORD}}"
          
      # 4to step (variables abiertas):
      - name: variables abiertas # variables abiertas
        run: |
          Imprimir las variables abiertas (VERSION_PROYECTO)
          echo "Versión de mi proyecto: $VERSION_PROYECTO"