# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Requerimiento e) Sistema operativo: linux
    runs-on: ubuntu-latest
    
    # Requerimientos g) y l) Definición de variables de entorno y variable abierta
    env:
      NOMBRES: Percy
      APELLIDOS: Zavala Muñoz
      EDAD: 30
      VERSION_PROYECTO: 3.0 

    steps:
      # Primer paso de la base que se mantiene (Checks-out your repository)
      - uses: actions/checkout@v4
      
      # *** INICIO DE LOS PASOS REQUERIDOS POR TU LISTA ***

      # Requerimiento h) Crear un 1er step:
      - name: presentación # h.1) llamado: presentación
        run: |
          # h.2) Imprimir las variables de entorno (NOMBRES, APELLIDOS, EDAD)
          echo "Nombres: $NOMBRES"
          echo "Apellidos: $APELLIDOS"
          echo "Edad: $EDAD"

      # Requerimiento i) Crear un 2do step:
      - name: datos generales # i.1) llamado: datos generales
        run: |
          # i.2) imprimir: "carrera de ingeniería de sistemas"
          echo "carrera de ingeniería de sistemas"
          
      # Requerimiento k) crear un 3er step (variables secretas):
      - name: variables de entorno secretas # k.1) llamado: variables de entorno secretas
        run: |
          # k.2) imprimir variables secretas (j.1: user, j.2: password)
          echo "user: ${{ secrets.USER }}"
          echo "password: ${{ secrets.PASSWORD }}"
          
      # Requerimiento ll) crear un 4to step (variables abiertas):
      - name: variables abiertas # ll.1) llamado: variables abiertas
        run: |
          # ll.2) imprimir las variables abiertas (VERSION_PROYECTO)
          echo "Versión de mi proyecto: $VERSION_PROYECTO"